package dk.bm.fido.auth.controllers;

import dk.bm.fido.auth.external.dtos.CredentialOptionsRequestDto;
import dk.bm.fido.auth.external.dtos.CredentialResponseDto;
import dk.bm.fido.auth.external.services.WSO2Service;
import org.springframework.http.MediaType;
import org.springframework.security.oauth2.client.OAuth2AuthorizedClient;
import org.springframework.security.oauth2.client.annotation.RegisteredOAuth2AuthorizedClient;
import org.springframework.security.oauth2.core.OAuth2AccessToken;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class RegistrationController {
    private final WSO2Service wso2Service;

    public RegistrationController(WSO2Service wso2Service) {
        this.wso2Service = wso2Service;
    }

    /**
     * Starts the process of registering a new FIDO2 device
     * @param authorizedClient the authorized client pulled from the authorization header
     * @return The credential JSON object to send to the client
     */
    @PostMapping(value = "/register/start", produces = MediaType.APPLICATION_JSON_VALUE)
    public CredentialOptionsRequestDto registerStart(@RegisteredOAuth2AuthorizedClient("wso2") OAuth2AuthorizedClient authorizedClient) {
        OAuth2AccessToken token = authorizedClient.getAccessToken();
        String bearerToken = token.getTokenType().getValue() + " " + token.getTokenValue();

        return wso2Service.startUserDeviceRegistration(bearerToken);
    }

    /**
     * Finishes the process of registering a new device
     * @param authorizedClient the authorized client pulled from the authorization header
     * @param challengeResponse public key generated by FIDO2 to be associated with the user in wso2
     * @return A JSON object with the successful credential registration
     */
    @PostMapping(value = "/register/finish", produces = MediaType.APPLICATION_JSON_VALUE)
    public CredentialResponseDto registerFinish(@RegisteredOAuth2AuthorizedClient("wso2") OAuth2AuthorizedClient authorizedClient, @RequestBody CredentialResponseDto challengeResponse) {
        OAuth2AccessToken token = authorizedClient.getAccessToken();
        String bearerToken = token.getTokenType().getValue() + " " + token.getTokenValue();

        return wso2Service.finishUserDeviceRegistration(bearerToken, challengeResponse);
    }
}
