provider:
  host: https://localhost:9443 #Change the host

  spring:
    security:
    oauth2:
      client:
      registration:
        wso2:
        client-name : WSO2 Identity Server
        client-id: LQTLEgDFil5Tyf0wS5KWUShkMDEa #Change client-id
        client-secret: uFwLrbBKhp74NWT1zBIjXuXuYUa # Change client-secret
        authorization-grant-type: authorization_code
        scope: openid
      provider:
        wso2:
        issuer-uri: ${provider.host}/oauth2/oidcdiscovery

    thymeleaf:
    cache: false